import { table } from "./tableType";


export const DATATABL: table[] = [
  {
    id:"#01",
      image :"./assets/images/products/1.png",
      name:"Metal Watch",
      progresscolor:"success-transparent",
    //  width:"40",
     status:"Delivered",
      text:"success",
     cost:14500,
     paymentmode:"Online Payment",
     clientname:"Sean Black",
     productId:"PRO12345"
    },
    {
      id:"#02",
        image :"./assets/images/products/3.png",
        name:"Teddy Bear",
        progresscolor:"info-transparent",
      //  width:"40",
       status:"Delivering",
        text:"info",
       cost:30000,
       paymentmode:"Cash on Delivery",
       clientname:"Evan Rees",
       productId:"PRO8765"
      },
      {
        id:"#03",
          image :"./assets/images/products/5.png",
          name:"Floral Frock",
          progresscolor:"danger-transparent",
        //  width:"40",
         status:"Delivering",
          text:"danger",
         cost:13200,
         paymentmode:"Online Payment",
         clientname:"David Wallace",
         productId:"PRO54321"
        },
        {
          id:"#04",
            image :"./assets/images/products/4.png",
            name:" Smart Watch",
            progresscolor:"warning-transparent",
          //  width:"40",
           status:"Pending",
            text:"warning",
           cost:15100,
           paymentmode:"Cash on Delivery",
           clientname:"Julia Bower",
           productId:"PRO97654"
          },
          {
            id:"#05",
              image :"./assets/images/products/6.png",
              name:"Gold Ring",
              progresscolor:"primary-transparent",
            //  width:"40",
             status:"Shipped",
              text:"primary",
             cost:5987,
             paymentmode:"Online Payment",
             clientname:"Kevin James",
             productId:"PRO4532"
            },
            {
              id:"#06",
                image :"./assets/images/products/8.png",
                name:"Girls Sandals",
                progresscolor:"info-transparent",
              //  width:"40",
               status:"Delivering",
                text:"info",
               cost:11987,
               paymentmode:"Cash on Delivery",
               clientname:"Theresa	Wright",
               productId:"PRO6789"
              },
              {
                id:"#07",
                  image :"./assets/images/products/7.png",
                  name:"Gray T-shirt",
                  progresscolor:"warning-transparent",
                //  width:"40",
                 status:"Pending",
                  text:"warning",
                 cost:4700,
                 paymentmode:"Online Payment",
                 clientname:"Sebastian	Black",
                 productId:"PRO4567"
                },
                {
                  id:"#08",
                    image :"./assets/images/products/2.png",
                    name:"Leather Watch",
                    progresscolor:"success-transparent",
                  //  width:"40",
                   status:"Delivered",
                    text:"success",
                   cost:678,
                   paymentmode:"Cash on Delivery",
                   clientname:"Kevin Glover",
                   productId:"PRO32156"
                  },
                  {
                    id:"#09",
                      image :"./assets/images/products/9.png",
                      name:"Formal Shoes",
                      progresscolor:"warning-transparent",
                    //  width:"40",
                     status:"Pending",
                      text:"warning",
                     cost:200,
                     paymentmode:"Online Payment",
                     clientname:"Yadira Acklin",
                     productId:"PRO16543"
                    },
                    {
                      id:"#10",
                        image :"./assets/images/products/10.png",
                        name:"Stylish Hoodie",
                        progresscolor:"danger-transparent",
                      //  width:"40",
                       status:"Cancelled",
                        text:"danger",
                       cost:99,
                       paymentmode:"Unpaid",
                       clientname:"John Wisely",
                       productId:"PRO74328"
                      },
          ]
