export const studentdata=[
    { ProductId: 1, ProductName: 'Chai', UnitPrice: 18.00, UnitsInStock: 39, ProductDesc: "High-quality tea", ProductLocation: "Delhi", ProductIssuieDate: "09-15-1996" },
    { ProductId: 2, ProductName: 'Chang', UnitPrice: 19.50, UnitsInStock: 17, ProductDesc: "A spicy sauce", ProductLocation: "Mumbai", ProductIssuieDate: "09-15-1996" },
    { ProductId: 3, ProductName: 'Aniseed Syrup', UnitPrice: 10.00, UnitsInStock: 13, ProductDesc: "Sweet syrup", ProductLocation: "Kolkata", ProductIssuieDate: "09-15-1996" },
    { ProductId: 4, ProductName: 'Chef Anton\'s Cajun Seasoning', UnitPrice: 22.00, UnitsInStock: 53, ProductDesc: "Spicy seasoning", ProductLocation: "Chennai", ProductIssuieDate: "12-12-2001" },
    { ProductId: 5, ProductName: 'Chef Anton\'s Gumbo Mix', UnitPrice: 21.35, UnitsInStock: 0, ProductDesc: "Cajun mix", ProductLocation: "Bangalore", ProductIssuieDate: "09-15-1996" },
    { ProductId: 6, ProductName: 'Grandma\'s Boysenberry Spread', UnitPrice: 25.00, UnitsInStock: 120, ProductDesc: "Fruit spread", ProductLocation: "Hyderabad", ProductIssuieDate: "09-09-2005" },
    { ProductId: 7, ProductName: 'Uncle Bob\'s Organic Dried Pears', UnitPrice: 30.00, UnitsInStock: 25, ProductDesc: "Dried pears", ProductLocation: "Delhi", ProductIssuieDate: "09-15-1996" },
    { ProductId: 8, ProductName: 'Northwoods Cranberry Sauce', UnitPrice: 40.00, UnitsInStock: 60, ProductDesc: "Cranberry sauce", ProductLocation: "Pune", ProductIssuieDate: "11-11-2007" },
    { ProductId: 9, ProductName: 'Mishi Kobe Niku', UnitPrice: 97.00, UnitsInStock: 10, ProductDesc: "Premium beef", ProductLocation: "Delhi", ProductIssuieDate: "09-15-1996" },
    { ProductId: 10, ProductName: 'Ikura', UnitPrice: 31.00, UnitsInStock: 31, ProductDesc: "Salmon roe", ProductLocation: "Ahmedabad", ProductIssuieDate: "09-15-1996" },
    { ProductId: 11, ProductName: 'Queso Cabrales', UnitPrice: 21.00, UnitsInStock: 22, ProductDesc: "Cheese", ProductLocation: "Kochi", ProductIssuieDate: "09-15-1996" },
    { ProductId: 12, ProductName: 'Queso Manchego La Pastora', UnitPrice: 38.00, UnitsInStock: 86, ProductDesc: "Manchego cheese", ProductLocation: "Delhi", ProductIssuieDate: "09-15-1996" },
    { ProductId: 13, ProductName: 'Konbu', UnitPrice: 6.00, UnitsInStock: 24, ProductDesc: "Edible seaweed", ProductLocation: "Gurgaon", ProductIssuieDate: "09-15-1996" },
    { ProductId: 14, ProductName: 'Tofu', UnitPrice: 23.25, UnitsInStock: 35, ProductDesc: "Soybean curd", ProductLocation: "Noida", ProductIssuieDate: "07-04-2016" },
    { ProductId: 15, ProductName: 'Genen Shouyu', UnitPrice: 15.50, UnitsInStock: 39, ProductDesc: "Soy sauce", ProductLocation: "Patna", ProductIssuieDate: "09-15-1996" },
    { ProductId: 16, ProductName: 'Pavlova', UnitPrice: 25.00, UnitsInStock: 30, ProductDesc: "Dessert", ProductLocation: "Delhi", ProductIssuieDate: "09-01-2018" },
    { ProductId: 17, ProductName: 'Alice Mutton', UnitPrice: 39.00, UnitsInStock: 19, ProductDesc: "Mutton", ProductLocation: "Mumbai", ProductIssuieDate: "09-15-1996" },
    { ProductId: 18, ProductName: 'Carnarvon Tigers', UnitPrice: 62.50, UnitsInStock: 42, ProductDesc: "Shrimp", ProductLocation: "Hyderabad", ProductIssuieDate: "09-15-1996" },
    { ProductId: 19, ProductName: 'Teatime Chocolate Biscuits', UnitPrice: 9.20, UnitsInStock: 25, ProductDesc: "Chocolate biscuits", ProductLocation: "Lucknow", ProductIssuieDate: "11-09-2018" },
    { ProductId: 20, ProductName: 'Sir Rodney\'s Marmalade', UnitPrice: 81.00, UnitsInStock: 40, ProductDesc: "Marmalade", ProductLocation: "Delhi", ProductIssuieDate: "10-04-2022" },
    { ProductId: 21, ProductName: 'Sir Rodney\'s Scones', UnitPrice: 10.00, UnitsInStock: 3, ProductDesc: "Scones", ProductLocation: "Kolkata", ProductIssuieDate: "09-15-1996" },
    { ProductId: 22, ProductName: 'Nord-Ost Matjeshering', UnitPrice: 25.00, UnitsInStock: 120, ProductDesc: "Pickled herring", ProductLocation: "Chennai", ProductIssuieDate: "09-15-1996" },
    { ProductId: 23, ProductName: 'Gorgonzola Telino', UnitPrice: 12.50, UnitsInStock: 16, ProductDesc: "Blue cheese", ProductLocation: "Pune", ProductIssuieDate: "05-11-2022" },
    { ProductId: 24, ProductName: 'Mascarpone Fabioli', UnitPrice: 32.00, UnitsInStock: 60, ProductDesc: "Cheese", ProductLocation: "Bangalore", ProductIssuieDate: "09-15-1996" },
    { ProductId: 25, ProductName: 'Geitost', UnitPrice: 2.50, UnitsInStock: 112, ProductDesc: "Brown cheese", ProductLocation: "Delhi", ProductIssuieDate: "12-02-2016" },
  ];
  